-- In SQL Shell
-- 1. for help \?
-- 2. list databases \l
-- 3. Create database CREATE DATABASE database_name
-- 4. Go to the different database \c database_name
-- 5. list all tables \d

-- Create Table in a database
-- CREATE tABLE products (
--     id INT,
--     name VARCHAR(50),
--     price INT,
--     on_sale boolean
-- );